### ISSUE TITLE
Github Action Failing

### ISSUE THREAD

**Issue by brauliolomeli** [Trampoline-CX/action-turbo-changed#215]
## 🐛 Bug Description / How to Reproduce

The GH action used to work but consistently fails since 2 hours ago, likely due to the recent Turbo release (v2.0.1). Last time it succeed was with turbo v1.13.4. 

Logs:

Run Trampoline-CX/action-turbo-changed@v1
  with:
    workspace: @foo/api
    from: HEAD^1
    to: HEAD
    working-directory: ./
    turbo-task-name: build
  
npm warn exec The following package was not found and will be installed: turbo@[2](https://github.com/bl/foo/actions/runs/9373318852/job/25807744777#step:3:2).0.1
Error: Error: Command failed: TURBO_TELEMETRY_DISABLED=1 TURBO_TELEMETRY_MESSAGE_DISABLED=1 npx turbo run build --filter="@foo/api...[HEAD^1...HEAD]" --dry-run=json
npm warn exec The following package was not found and will be installed: turbo@2.0.1

## ✅ Expected behavior

The action doesn't fail

**Comment by gbartlett9089** [comment]
Also seeing the same issue.. Thanks for submitting this @brauliolomeli

**Comment by alexbchr** [comment]
@brauliolomeli @gbartlett9089  Thanks for reporting this issue! We had the same behaviour in our internal repositories. PR #216 fixed the issue (latest of Turbo v1 should be used now).

I'll try to follow-up soon with an update to support Turbo v2, but open to PRs as well if anyone has the chance to!

**Comment by ludalex** [comment]
@alexbchr any chance you managed to work on supporting Turbo v2? I'm more than willing to provide support with testing my large Turbo v2 app if that's of any help.

**Comment by alexbchr** [comment]
> @alexbchr any chance you managed to work on supporting Turbo v2? I'm more than willing to provide support with testing my large Turbo v2 app if that's of any help.

Unfortunately no we didn't have the time to work on it. We have fairly large existing Turbo v1 codebases that we plan to migrate to V2 and that can test the Action on. We plan to do so in the next month or so. If we need further testing before testing, I'll release a beta version that I'll post here as soon as it's available.

**Comment by alexbchr** [comment]
Also, just to make things easier to find for everyone and to know how many people are interested in the V2 upgrade, I opened #241. Please react to it if interested in this feature! 👍
