### ISSUE TITLE
feature request: the action should return a list of the packages that have changed as part of the output.

### ISSUE THREAD

**Issue by mikias** [Trampoline-CX/action-turbo-changed#24]
# Summary

feature request: the action should return a list of the packages that have changed as part of the output. This can let the changed packages to be used in down stream jobs via a matrix. @alexbchr

**Comment by alexbchr** [comment]
Good idea, will try to implement when my backlog opens up in the following weeks. Pull requests are welcome!

**Comment by alexbchr** [comment]
Hi @mikias, I feel like I can reopen this, unless you found some workaround?

**Comment by alexbchr** [comment]
Reopening, as I feel it should be implemented as well. For now, I am a bit short on time to do it, but keeping in mind for later. I am also open to PRs

**Comment by alexbchr** [comment]
This is now released on version `1.1` of the action 🚀
